# Generated by Django 5.0.6 on 2024-05-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subheading',
            name='post',
        ),
        migrations.DeleteModel(
            name='CodeBlock',
        ),
        migrations.DeleteModel(
            name='Subheading',
        ),
    ]
